### ISSUE TITLE
Form key on first page view incorrect

### ISSUE THREAD

**Issue by 0859170** [nexcess/magento-turpentine#753]
When I start my session on a product page of my Magento store, I get different form_key values in the HTML of the page.
The form_key in the action url is different from the form_key in the hidden input which is different than the form_key in the url that adds the product to the wishlist, and all of them are not the correct form_key that is linked to my session.

I do see a form_key request going to Nginx on the first page view, so I don't think that Varnish sees me as a crawler..

When I refresh the page, the form keys are all the same and correct.

**Comment by brucemead** [comment]
I'm seeing the same issue. One session yielded 3 different form keys.

**Comment by abubner** [comment]
Hi, we have the same problem! Do anyone knows a solution?

**Comment by evensis** [comment]
https://github.com/nexcess/magento-turpentine/pull/516

**Comment by 0859170** [comment]
Thank you.
I implemented and tested this change. Now all form_key values are the same, but still invalid. When I refresh the page the form_keys change to the correct ones.

**Comment by markus-g** [comment]
We have the same problem.
The fix from #516 reduces the calls of getFormKey (which is good too), but doesn't fix the add to cart problem. On the first visit the form_key is always wrong. After a reload of the page, it works.

**Comment by aricwatson** [comment]
Right now the best fix seems to be a tweak to the VCL that bypasses varnish on the first page load of a session. This is not idea so we're still working on a better fix - but you can go with it now if you need to: https://github.com/nexcess/magento-turpentine/issues/345#issuecomment-106096817

This appears to be the same as (https://github.com/nexcess/magento-turpentine/issues/345) so I'm going to close this issue.
