### ISSUE TITLE
Magento : Due to varnish wrong customer ID geting

### ISSUE THREAD

**Issue by anmolnagpal** [nexcess/magento-turpentine#870]
We are  using turpentine extension for varnish with magento and my magento version is magento1.8

I am trying to get customer ID for GA script , When I logged In and goto any category page then I logout and try to login with another customer . Issue is at this time it is display previous customer ID which is wrong

Note : When I cleared varnish cache then it's working fine

Can you please Provide Solution. ASAP

**Comment by miguelbalparda** [comment]
@anmolnagpal how are you setting ESI policies for you GA block?

**Comment by anmolnagpal** [comment]
My Block is :
  <reference name="head">
            <block type="aromicon_gua/gua" name="google_universial_analytics" template="aromicon/gua/gua.phtml" />
        </reference>


I am adding to this block in ESI like this 


 <reference name="google_universial_analytics">
        <action method="setEsiOptions">
            <params>
                <access>private</access>
                <ttl>0</ttl>
            </params>
        </action>
    </reference>

   <reference name="google_universial_analytics">
        <action method="setCacheLifetime">0</action>
    </reference>

**Comment by miguelbalparda** [comment]
Would you mind pasting the block again?

**Comment by anmolnagpal** [comment]
![snip20150729_1](https://cloud.githubusercontent.com/assets/4303310/8957200/73b63df2-361a-11e5-8b75-77802131c4a2.png)

**Comment by miguelbalparda** [comment]
It seems to be correct. Which Turpentine version are you using? We pushed a new version yesterday with a lot of improvements, I suggest you to try it.

**Comment by anmolnagpal** [comment]
We are using 0.6.1 version for  Turpentine extenstion , I have also update new version 0.6.3 but it still not working

**Comment by miguelbalparda** [comment]
Are you using Magento block cache? Only the Turpentine caches should be enabled.

**Comment by anmolnagpal** [comment]
Please find attachment for varnish , cache option setting  and vcl file 

P.F.A varnish_option.png
P.F.A varnish_cache_option.png
P.F.A default_main.vcl


We are geting below logs in the turpentine.log file
2015-07-30T05:59:09+00:00 DEBUG  TURPENTINE: Cleared ESI cache for client (7g9iabotnfjl27q31e7h346k14) on event: customer_logout
2015-07-30T05:59:09+00:00 INFO  TURPENTINE: Checking ESI block candidate: root
2015-07-30T05:59:09+00:00 INFO  TURPENTINE: Checking ESI block candidate: head
2015-07-30T05:59:09+00:00 INFO  TURPENTINE: Checking ESI block candidate: js_cookies
2015-07-30T05:59:09+00:00 INFO  TURPENTINE: Checking ESI block candidate: optional_zip_countries
2015-07-30T05:59:10+00:00 INFO  TURPENTINE: Checking ESI block candidate: fbintegrator.meta-tags
2015-07-30T05:59:10+00:00 INFO  TURPENTINE: Checking ESI block candidate: google_universial_analytics

![varnish_cache_option](https://cloud.githubusercontent.com/assets/4303310/8976879/af8451f2-36b0-11e5-8fb5-ecf22f83747c.png)
![varnish_option](https://cloud.githubusercontent.com/assets/4303310/8976880/af8623c4-36b0-11e5-8e22-92eb7d1aeb7d.png)

**Comment by magentocj** [comment]
@miguelbalparda   Any update please

**Comment by miguelbalparda** [comment]
Please disable all the caches in System - Cache management and leave only the last 2 from Turpentine.

**Comment by magentocj** [comment]
@miguelbalparda  Thanks for update 

Yes, I have disabled all the cache excluding the last 2 from Turpentine but  it is not working  :( 

It is display privious customer ID on varnish cached page

**Comment by magentocj** [comment]
@miguelbalparda  can we Blacklist any specific block

**Comment by magentocj** [comment]
@miguelbalparda Any update please guys

**Comment by miguelbalparda** [comment]
I strongly believe the issue you are facing is related to your theme structure, we have never faced this issue in the past. It is also possible you are using an extension for google analytics since the regular analytics block is called google_analytics and not google_universial_analytics. I suggest you to contact both your theme provider and your GA extension provider about this issue in particular.

**Comment by magentocj** [comment]
@miguelbalparda 
Thanks for update 

I  have disabled  my custom  google_universial_analytic  module and try get customer ID on product view page , but it's display privous customer ID

**Comment by magentocj** [comment]
@miguelbalparda  Is this issue related to old magento version , I am using magento 1.8V

Thanks

**Comment by miguelbalparda** [comment]
Without a proper block containing the info you are being cached as a part of the page you are seeing probably. Try to wrap the ID call inside a block and set ESI policies to it.

**Comment by magentocj** [comment]
@miguelbalparda 
IF I add my block in reference name  in head   then It is working find  , can you please tell me why this not working without add reference name  in head 

Thanks

**Comment by magentocj** [comment]
Any upate please

**Comment by magentocj** [comment]
@miguelbalparda 
Unable to see ESI START message after add to block in ESI

**Comment by miguelbalparda** [comment]
@magentocj please stop asking for updates. We are working on this and as you see, if you move the call to another block you are seeing positive results which means the module you are using might be the cause of your issue.

**Comment by miguelbalparda** [comment]
Closed for lack of feedback.
